require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'myReactNativeProject' do
  use_unimodules!
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])
  
  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!({ 'Flipper' => '0.80.0' })
  #   post_install do |installer|
  #     flipper_post_install(installer)
  #   end
  # end
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable arm64 builds for the simulator
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
