import LocalizedStrings from 'react-native-localization';

export const initiateURL = {
  dev: 'https://dev-api.portone.cloud/api/',
  staging: 'https://stage-api.portone.cloud/api/',
  prod: 'https://api.portone.cloud/api/',
};

export const baseURL = {
  dev: 'https://dev-api.portone.cloud/',
  staging: 'https://stage-api.portone.cloud/',
  prod: 'https://api.portone.cloud/',
};

export const fetchTokenizationURL = {
  dev: 'https://dev-api.portone.cloud/api/tokenization/tokenize-card',
  staging: 'https://stage-api.portone.cloud/api/tokenization/tokenize-card',
  prod: 'https://api.portone.cloud/api/tokenization/tokenize-card',
};

export const api = {
  initiatePayment: 'initiatePayment',
};

export const bodyParams = {
  portOneKey: 'key',
  paymentChannel: 'pmt_channel',
  paymentMethod: 'pmt_method',
  merchantOrderId: 'merchant_order_id',
  amount: 'amount',
  currency: 'currency',
  billingDetails: 'billing_details',
  shippingDetails: 'shipping_details',
  orderDetails: 'order_details',
  successUrl: 'success_url',
  failureUrl: 'failure_url',
  signatureHash: 'signature_hash',
  redirectUrl: 'redirect_url',
  environment: 'environment',
  source: 'source',
  merchantDetails: 'merchant_details',
  paymentLink: 'payment_link',
};

export const requiredParams = [
  'portOneKey',
  'paymentChannel',
  'paymentMethod',
  'merchantOrderId',
  'amount',
  'currency',
  'signatureHash',
  'orderDetails',
  'redirectUrl',
  'failureUrl',
  'successUrl',
  'environment',
  'source',
];

export const webBodyParams = {
  portOneKey: 'chaipay_key',
  merchantOrderId: 'merchant_order_id',
  amount: 'amount',
  currency: 'currency',
  billingDetails: 'billing_details',
  shippingDetails: 'shipping_details',
  orderDetails: 'order_details',
  successUrl: 'success_url',
  failureUrl: 'failure_url',
  signatureHash: 'signature_hash',
  mobileRedirectUrl: 'mobile_redirect_url',
  merchantDetails: 'merchant_details',
  countryCode: 'country_code',
  expiryHours: 'expiry_hours',
  source: 'source',
  description: 'description',
  showShippingDetails: 'show_shipping_details',
  showBackButton: 'show_back_button',
  defaultGuestCheckout: 'default_guest_checkout',
  isCheckoutEmbed: 'is_checkout_embed',
  environment: 'environment',
};

export const webRequiredParams = [
  'portOneKey',
  'merchantOrderId',
  'amount',
  'currency',
  'orderDetails',
  'successUrl',
  'failureUrl',
  'signatureHash',
  'mobileRedirectUrl',
  'merchantDetails',
  'countryCode',
  'expiryHours',
  'source',
  'description',
  'environment',
];

export const WHITE_COLOR = 'white';
export const APP_THEME_COLOR = '#FF2A2A';
export const OLD_APP_THEME_COLOR = '#3D3D3D';
export const IMAGE_BACKGROUND_COLOR = '#F5F5F5';
export const TRANSPARENT = 'transparent';
export const LIGHTGRAY = 'lightgray';
export const BLACK = 'black';
export const DARKBLACK = '#000000';
export const DARKGRAY = 'darkgray';
export const HEDER_TITLES = '#424347';
export const ORDERTEXT = '#3E3E3E';
export const SORTANDFILTER = '#3D3D3D';
export const descriptionText = '#8F8F9F';
export const BACKGROUND_COLOR = '#F4F4F4';

export const BORDERCOLOR = '#E0E0E0';
export const GRAYSHADE = '#828282';
export const HEADERBLACK = '#141414';
export const SUCCESS_COLOR = '#3CAF47';

//fontWeight
export const BOLD = 'bold';

export const languageData = [
  {
    name: 'Thai',
    code: 'th-TH',
    languageCode: 'th',
    currency: 'THB',
  },
  {
    name: 'Vietnamese',
    code: 'vn-VN',
    languageCode: 'vn',
    currency: 'VND',
  },
  {
    name: 'English',
    code: 'en-US',
    languageCode: 'en',
    currency: 'USD',
  },
];

export let strings = new LocalizedStrings({
  'en-US': {
    BNPL: 'BNPL',
    bankTransfer: 'Bank Transfer',
    QRcode: 'QR Code',
    netBanking: 'Net banking',
    expiryDate: 'Expiry Date',
    searchByWallets: ' Search by Channels',
    poweredBy: 'Powered by',
    creditOrDebitCard: 'Debit / Credit Card',
    paymentMethods: 'Payment Methods',
    taxes: 'Taxes',
    summary: 'Summary',
    orderDetails: 'Order Details',
    netPayable: 'Net payable',
    paymentConfirmation: 'Payment Confirmation',
    cancel: 'Cancel',
    enterMobileNumber: 'Enter Mobile Number',
    saveForLater: 'Save for later',
    enterCardName: 'Enter Card Name',
    invalidCardDetails: 'Invalid card details',
    modalClosedExplicitly: 'Modal closed explicitly',
    price: 'Price',
    price_details: 'Price Details',
    items_listed: 'items listed',
    sort: 'Sort',
    buy_now: 'Buy Now',
    checkout: 'Checkout',
    saved_payment_method: 'Saved Payment Method',
    payNow: 'Pay Now',
    other_payment_options: 'Other Payment options',
    wallets: 'Wallets',
    credit_card: 'Credit Card',
    safe_and_secure_payments: 'Safe and Secure Payments',
    card_number: 'Card Number',
    enter_mobile_no: 'Enter Mobile No',
    other_options: 'Other Options',
    success: 'success',
    fail: 'fail',
    this_field_is_required: 'This field is required.',
    invalid_mobile_number_error: 'Please enter a valid number.',
    otp_has_been_sent: 'OTP has been sent to your',
    error_no_internet_connectivity:
      'No internet connection. Please check your internet settings and try again.',
    error_oops_something_went_wrong:
      'Oops! Something went wrong, please try again…',
    error_verify_otp: 'Kindly verify received OTP.',
    select_one_payment_method: 'Select At least One Payment Method',
    fill_all_card_details: 'Fill All the Card Details',

    continue_shopping: 'Continue Shopping',
    phone_no: 'Phone No:',
    verify: 'Verify',
    merchant_order_ref: 'Merchant Order Ref:',
    channel_order_ref: 'Channel Order Ref:',
    status: 'Status',
    payment_successful: 'Payment Successful',
    payment_failed: 'Payment Failed',
    card_holder_name: 'Card Holder Name',
    month: 'Month',
    year: 'Year',
    no_data_available: 'No Data Available',
    no_saved_cards: 'No Saved Cards',
    get_otp: 'Get Otp',
    web_checkout: 'Web Checkout',
    custom_checkout: 'Custom Checkout',
    please_enter_valid_mobile_no: 'Please enter valid mobile no',
    please_enter_valid_otp: 'Please enter valid OTP',
    payout: 'Payout',
    payout_status: 'Payout Status',
    payment_type: 'Payment Type',
    dismiss: 'dismiss',
    error_no_app_found: 'No Apps Found',
    no_intent_client_found: 'No Intent Client Found',
    tap_to_retry: 'Tap to Retry',
    something_went_wrong: 'Oops.. Something went wrong!!',
    no_internet_connection: 'No Internet Connection',
    home: 'Home',
    profile: 'Profile',
    my_cart: 'My cart',
    saved_cards: 'Saved Cards',
    ATM_card: 'ATM Card',
    total: 'Total',
    exp_date: 'Exp Date',
    cvv: 'CVV',
    alert_option:
      'Please choose one of the below UI methods to proceed further',
    Change_Language_Msg:
      'Please choose your language, restart is required to apply to change.',
    next: 'Next',
    order: 'Order',
    delivery: 'Delivery',
    transaction_failed: 'Transaction Failed',
    transaction_success: 'Your order is placed successfully!',
    amount_toPaid: 'Amount to be paid',
    amount_paid: 'Amount Paid',
    shipping_address: 'Shipping Address',
    chose_payment_option: 'Choose a payment option',
    get_saved_cards: 'Get Saved cards flow',
    language_selection: 'Language selection',
  },
  'th-TH': {
    language_selection: 'การเลือกภาษา',
    get_saved_cards: 'รับโฟลว์การ์ดที่บันทึกไว้',
    chose_payment_option: 'เลือกตัวเลือกการชำระเงิน',
    BNPL: 'BNPL',
    bankTransfer: 'โอนเงินผ่านธนาคาร',
    QRcode: 'คิวอาร์โค้ด',
    netBanking: 'เน็ตแบงกิ้ง',
    expiryDate: 'วันหมดอายุ',
    searchByWallets: 'ค้นหาตามช่อง',
    poweredBy: 'ขับเคลื่อนโดย',
    creditOrDebitCard: 'เดบิต / บัตรเครดิต',
    paymentMethods: 'วิธีการชำระเงิน',
    taxes: 'ภาษี',
    summary: 'สรุป',
    orderDetails: 'รายละเอียดการสั่งซื้อ',
    netPayable: 'เจ้าหนี้สุทธิ',
    paymentConfirmation: 'ยืนยันการชำระเงิน',
    enterMobileNumber: 'ใส่เบอร์มือถือ',
    next: 'ต่อไป',
    saveForLater: 'บันทึกในภายหลัง',
    enterCardName: 'ใส่ชื่อบัตร',
    invalidCardDetails: 'รายละเอียดบัตรไม่ถูกต้อง',
    modalClosedExplicitly: 'Modal ปิดอย่างชัดแจ้ง',
    cancel: 'ยกเลิก',

    price: 'ราคา',
    price_details: 'รายละเอียดราคา',
    items_listed: 'รายการที่ระบุไว้',
    sort: 'เรียงลำดับ',
    buy_now: 'ซื้อเลย',
    checkout: 'เช็คเอาท์',
    saved_payment_method: 'วิธีการชำระเงินที่บันทึกไว้',
    payNow: 'จ่ายตอนนี้',
    other_payment_options: 'ตัวเลือกการชำระเงินอื่น ๆ',
    wallets: 'กระเป๋าสตางค์',
    credit_card: 'บัตรเครดิต',
    safe_and_secure_payments: 'การชำระเงินที่ปลอดภัยและมั่นคง',
    card_number: 'หมายเลขบัตร',
    enter_mobile_no: 'ใส่เบอร์มือถือ',
    other_options: 'ตัวเลือกอื่น',
    success: 'สำเร็จ',
    fail: 'ล้มเหลว',
    this_field_is_required: 'ต้องกรอกช่องนี้.',
    invalid_mobile_number_error: 'โปรดป้อนหมายเลขอินเดียที่ถูกต้อง',
    otp_has_been_sent: 'ส่ง OTP ไปที่ . แล้ว',
    error_no_internet_connectivity:
      'ไม่มีการเชื่อมต่ออินเทอร์เน็ต. โปรดตรวจสอบการตั้งค่าอินเทอร์เน็ตของคุณและลองอีกครั้ง',
    error_oops_something_went_wrong: 'อ๊ะ! มีบางอย่างผิดพลาด โปรดลองอีกครั้ง…',
    error_verify_otp: 'กรุณาตรวจสอบรหัส OTP ที่ได้รับ',
    select_one_payment_method: 'เลือกวิธีการชำระเงินอย่างน้อยหนึ่งวิธี',
    fill_all_card_details: 'กรอกรายละเอียดบัตรทั้งหมด',
    continue_shopping: 'ช้อปปิ้งต่อ',
    phone_no: 'หมายเลขโทรศัพท์:',
    verify: 'ตรวจสอบ',
    merchant_order_ref: 'อ้างอิงคำสั่งซื้อของผู้ค้า:',
    channel_order_ref: 'ช่องทางการสั่งซื้ออ้างอิง:',
    status: 'สถานะ',
    payment_successful: 'การชำระเงินสำเร็จ',
    payment_failed: 'การชำระเงินล้มเหลว',
    card_holder_name: 'ชื่อผู้ถือบัตร',
    month: 'เดือน',
    year: 'ปี',
    no_data_available: 'ไม่มีข้อมูลที่สามารถใช้ได้',
    no_saved_cards: 'ไม่มีการ์ดที่บันทึกไว้',
    get_otp: 'รับ Otp',
    web_checkout: 'เว็บชำระเงิน',
    custom_checkout: 'ชำระเงินแบบกำหนดเอง',
    please_enter_valid_mobile_no: 'โปรดป้อนหมายเลขโทรศัพท์มือถือที่ถูกต้อง',
    please_enter_valid_otp: 'โปรดป้อน OTP . ที่ถูกต้อง',
    payout: 'การจ่ายเงิน',
    payout_status: 'สถานะการจ่ายเงิน',
    payment_type: 'ประเภทการชำระเงิน',
    dismiss: 'ยกเลิก',
    error_no_app_found: 'ไม่พบแอป',
    no_intent_client_found: 'ไม่พบแอปที่ต้องการในเครื่องนี้',
    tap_to_retry: 'แตะเพื่อลองใหม่',
    something_went_wrong: 'อ๊ะ.. มีบางอย่างผิดพลาด!!',
    no_internet_connection: 'ไม่มีการเชื่อมต่ออินเทอร์เน็ต',
    home: 'บ้าน',
    profile: 'ประวัติโดยย่อ',
    my_cart: 'รถเข็นของฉัน',
    saved_cards: 'การ์ดที่บันทึกไว้',
    ATM_card: 'บัตรเอทีเอ็ม',
    total: 'รวม',
    exp_date: 'วันหมดอายุ',
    cvv: 'CVV',
    alert_option: 'โปรดเลือกหนึ่งในวิธี UI ด้านล่างเพื่อดำเนินการต่อ',
    Change_Language_Msg:
      'กรุณาเลือกภาษาของคุณ จำเป็นต้องรีสตาร์ทเพื่อนำไปใช้ในการเปลี่ยนแปลง',
    order: 'คำสั่ง',
    delivery: 'จัดส่ง',
    transaction_failed: 'การทำธุรกรรมล้มเหลว',
    transaction_success: 'สั่งซื้อของคุณสำเร็จแล้ว!',
    amount_toPaid: 'จำนวนที่ต้องจ่าย',
    amount_paid: 'จำนวนเงินที่จ่าย',
    shipping_address: 'ที่อยู่จัดส่ง',
  },
  'vn-VN': {
    language_selection: 'การเลือกภาษา',
    get_saved_cards: 'รับโฟลว์การ์ดที่บันทึกไว้',
    chose_payment_option: 'เลือกตัวเลือกการชำระเงิน',
    BNPL: 'BNPL',
    bankTransfer: 'Chuyển khoản ngân hàng',
    QRcode: 'Mã QR',
    netBanking: 'Ngân hàng trực tuyến',
    saveForLater: 'Tiết kiệm cho sau này',
    expiryDate: 'Ngày hết hạn',
    searchByWallets: 'Tìm kiếm theo kênh',
    poweredBy: 'Được cung cấp bởi',
    creditOrDebitCard: 'Thẻ tín dụng ghi nợ',
    paymentMethods: 'Phương thức thanh toán',
    taxes: 'thuế',
    summary: 'Bản tóm tắt',
    orderDetails: 'Chi tiết đơn hàng',
    netPayable: 'Phải trả ròng',
    paymentConfirmation: 'Xác nhận thanh toán',
    checkout: 'Thủ tục thanh toán',
    enterMobileNumber: 'Nhập số điện thoại di động',
    next: 'Kế tiếp',
    enterCardName: 'Nhập tên thẻ',
    invalidCardDetails: 'Chi tiết thẻ không hợp lệ',
    modalClosedExplicitly: 'Phương thức đã đóng một cách rõ ràng',
    cancel: 'Hủy bỏ',

    price: 'Giá bán',
    price_details: 'Chi tiết giá cả',
    items_listed: 'mặt hàng được liệt kê',
    sort: 'Sắp xếp',
    buy_now: 'Tiến hành thanh toán',
    saved_payment_method: 'Phương thức thanh toán đã lưu',
    payNow: 'Thanh toán ngay',
    other_payment_options: 'Các tùy chọn thanh toán khác',
    wallets: 'Ví',
    credit_card: 'Thẻ tín dụng',
    safe_and_secure_payments: 'Thanh toán An toàn và Bảo mật',
    card_number: 'Số thẻ',
    enter_mobile_no: 'Nhập số điện thoại di động',
    success: 'Thành công',
    fail: 'Thất bại',
    this_field_is_required: 'Thông tin này là bắt buộc.',
    invalid_mobile_number_error: 'Vui lòng nhập một số Ấn Độ hợp lệ',
    otp_has_been_sent: 'OTP đã được gửi đến',
    error_no_internet_connectivity:
      'Không có kết nối Internet. Vui lòng kiểm tra cài đặt internet của bạn và thử lại.',
    error_oops_something_went_wrong: 'Oops! Đã xảy ra sự cố, vui lòng thử lại',
    error_verify_otp: 'Vui lòng xác minh OTP đã nhận.',
    select_one_payment_method: 'Chọn ít nhất một phương thức thanh toán',
    fill_all_card_details: 'Điền  tất cả các thông tin thẻ',
    continue_shopping: 'Tiếp tục mua sắm',
    phone_no: 'Số điện thoại:',
    verify: 'Xác nhận',
    merchant_order_ref: 'Tham chiếu đơn đặt hàng của người bán:',
    channel_order_ref: 'Tham chiếu đặt hàng kênh:',
    status: 'Trạng thái',
    payment_successful: 'Thanh toán thành công',
    payment_failed: 'Thanh toán không thành công',
    card_holder_name: 'Tên chủ thẻ',
    month: 'Tháng',
    year: 'Năm',
    no_data_available: 'Không có dữ liệu',
    no_saved_cards: 'Không có thẻ đã lưu',
    get_otp: 'Nhận Otp',
    web_checkout: 'Checkout trên web',
    custom_checkout: 'Tùy chỉnh Checkout',
    please_enter_valid_mobile_no: 'Vui lòng nhập số điện thoại di động hợp lệ',
    please_enter_valid_otp: 'Vui lòng nhập mã OTP hợp lệ',
    payout: 'Thanh toán chi tiền',
    payout_status: 'Trạng thái Thanh toán chi tiền',
    payment_type: 'Hình thức thanh toán',
    dismiss: 'Hủy bỏ',
    error_no_app_found: 'Không tìm thấy ứng dụng nào',
    no_intent_client_found: 'Không tìm thấy khách hàng có ý định',
    tap_to_retry: 'Chạm để thử lại',
    something_went_wrong: 'Oops! Đã xảy ra sự cố!',
    no_internet_connection: 'Không có kết nối Internet',
    home: 'Nhà',
    profile: 'Hồ sơ',
    my_cart: 'Giỏ hàng của tôi',
    saved_cards: 'Thẻ đã lưu',
    other_options: 'Sự lựa chọn khác',
    ATM_card: 'Thẻ ATM',
    total: 'Toàn bộ',
    exp_date: 'Ngày hết hạn',
    cvv: 'CVV',
    alert_option:
      'Vui lòng chọn một trong các phương pháp giao diện người dùng bên dưới để tiếp tục',
    Change_Language_Msg:
      'Vui lòng chọn ngôn ngữ của bạn, khởi động lại là bắt buộc để áp dụng thay đổi.',
    order: 'Đặt hàng',
    delivery: 'Chuyển',
    transaction_failed: 'Giao dịch không thành công',
    transaction_success: 'Đơn hàng của bạn đã được đặt thành công!',
    amount_toPaid: 'Số tiền phải trả',
    amount_paid: 'Số tiền đã trả',
    shipping_address: 'Địa chỉ giao hàng',
  },
});

export const locale = () => strings;
